# Generated by Django 5.2.3 on 2025-06-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_ingredient_quantity_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='meal_type',
            field=models.CharField(default='朝食', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='menu',
            field=models.TextField(default='おかずセットA'),
            preserve_default=False,
        ),
    ]
